services:
  chrome:
    image: selenium/node-chrome:4.24.0-20240830
    shm_size: 2gb
    depends_on:
      - selenium-hub
    ports:
      - "7901:7900"
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  edge:
    image: selenium/node-edge:4.24.0-20240830
    shm_size: 2gb
    depends_on:
      - selenium-hub
    ports:
      - "7902:7900"
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  firefox:
    image: selenium/node-firefox:4.24.0-20240830
    shm_size: 2gb
    depends_on:
      - selenium-hub
    ports:
      - "7903:7900"
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  selenium-hub:
    image: selenium/hub:4.24.0-20240830
    container_name: selenium-hub
    ports:
      - "4444:4444"

  test:
    build: .
    volumes:
      - ./screenshot:/app/screenshot
    command: [ "--hub-host", "http://selenium-hub:4444/wd/hub"]
    restart: on-failure
    depends_on:
      - chrome
      - edge
      - firefox